# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Build AppImage
        run: |
          sudo apt-get -y install zsync desktop-file-utils libfuse2 graphicsmagick-imagemagick-compat
          wget -q "https://raw.githubusercontent.com/AppImage/pkg2appimage/master/pkg2appimage"
          bash -ex pkg2appimage dotnet-runtime.yml
          export ARCH="$(uname -m)"
          VERSION=$(wget -qO- "https://github.com/dotnet/runtime/tags" | grep -Eo /v8.* | sed 's|"| |;s|/v||g' | head -1 | awk '{print $1}')
          URUNTIME="https://github.com/VHSgunzo/uruntime/releases/latest/download/uruntime-appimage-dwarfs-$ARCH"
          URUNTIME_LITE="https://github.com/VHSgunzo/uruntime/releases/latest/download/uruntime-appimage-dwarfs-lite-$ARCH"
          wget --retry-connrefused --tries=30 "$URUNTIME" -O ./uruntime
          wget --retry-connrefused --tries=30 "$URUNTIME_LITE" -O ./uruntime-lite
          chmod +x ./uruntime*
          UPINFO="gh-releases-zsync|$(echo "$GITHUB_REPOSITORY" | tr '/' '|')|test|*$ARCH.AppImage.zsync"
          ./uruntime-lite --appimage-addupdinfo "$UPINFO"
          ./uruntime --appimage-mkdwarfs -f --set-owner 0 --set-group 0 --no-history --no-create-timestamp --compression zstd:level=22 -S26 -B8 --header uruntime-lite -i ./dotnet-runtime/dotnet-runtime.AppDir -o ./dotnet-runtime-"$VERSION"-"$ARCH".AppImage
          zsyncmake *.AppImage -u *.AppImage
          echo $PWD
          ls -al

      - name: Release
        uses: marvinpinto/action-automatic-releases@6273874b61ebc8c71f1a61b2d98e234cf389b303
        with:
          title: test build
          automatic_release_tag: test
          prerelease: false
          draft: false
          files: /home/runner/work/dotnet-runtime_AppImage/dotnet-runtime_AppImage/dotnet-runtime-*-$ARCH.AppImage*
          repo_token: ${{ secrets.PATN }}
