name: check

on:
  schedule:
  - cron: "0 */12 * * *"

jobs:
  new-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PATN }}
    - name: get-latest-version
      run: |
        VERSION="$(wget -qO- "https://github.com/dotnet/runtime/tags" | grep -Eo /v7.* | sed 's|"| |;s|/v||g' | head -1 | awk '{print $1}')"
        last=$(tail -n1 .build | awk '{print $4}')

        if [ "$last" != "$VERSION" ]; then
          echo "$(date -u --rfc-3339=seconds) Version $VERSION" >> .build
        fi
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Trigger build for new version
        branch: main
